### ISSUE TITLE
About bin>events file generation

### ISSUE THREAD

**Issue by GUEVARA1962** [Paxlord/PaxMHFZQuestEditor#4]
Thank you for the great tool!
But I'm having a problem.
Unable to create event file in bin>events.
Does this tool have the ability to generate it?

**Comment by Paxlord** [comment]
Hello, You should be able to generate an event in the "Misc Params" category. There's an "Event" tab where you can set a few event specific parameters and generate an event .bin by pressing save 
![image](https://github.com/Paxlord/PaxMHFZQuestEditor/assets/19719025/37ea9dba-e1c7-4db0-bbb7-e3579a69617a)

**Comment by GUEVARA1962** [comment]
Oh! Thank you for letting me know! ! It looks like you can escape from the maze.

**Comment by GUEVARA1962** [comment]
THX!
I achieved my goal.

**Comment by GUEVARA1962** [comment]
THX!
I achieved my goal.
